version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-ndk-r17b
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init

      # install dependencies
      - run: sudo apt-get update && sudo apt-get install file build-essential maven

      # download dependencies
      - restore_cache:
          key: spokestack-android-maven-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          key: spokestack-android-maven-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      # build and verify
      - run: mvn -DrepoToken=${COVERALLS_REPO_TOKEN} test jacoco:report coveralls:report
      - run: mvn checkstyle:check

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
